services:
  streamer_1:
    build: 
      context: ./streamer_1
      dockerfile: dockerfile
    container_name: iot_streamer_node_1
    restart: unless-stopped
    ports:
      - "8554:8554"

  inference:
    build:
      context: .
      dockerfile: inference/dockerfile
    container_name: par_inference_node
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./exports:/app/exports
    environment:
      - STREAM_SOURCE=rtsp://streamer_1:8554/live/stream
      - MODEL_PATH=/app/inference/models/baseline_v4_prod.onnx  
      - TZ=Europe/Stockholm
    depends_on:
      - streamer_1