services:
  streamer_1:
    build: 
      context: ./streamer_1
      dockerfile: dockerfile
    container_name: iot_streamer_node_1
    restart: unless-stopped
    ports:
      - "8554:8554"

  inference:
    build: 
      context: ./inference
      dockerfile: dockerfile
    container_name: par_inference_node
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "5000:5000"
    environment:
      - STREAM_SOURCE=rtsp://streamer_1:8554/live/stream
      - MODEL_PATH=/app/baseline_v4_prod.onnx
      - FLASK_PORT=5000
    depends_on:
      - streamer_1